CREATE TABLE "PUBLIC"."USERS"
(
   ID bigint generated by default as identity,
   CREATION_TIME timestamp NOT NULL,
   EMAIL varchar(255) NOT NULL,
   FIRST_NAME varchar(255) NOT NULL,
   LAST_NAME varchar(255) NOT NULL,
   MODIFICATION_TIME timestamp NOT NULL,
   USERNAME varchar(255) NOT NULL,
   VERSION bigint,
   primary key (id)
)
;

